Fix broken `timeout` in serial case
dbbs-lab/bsb-test pull request #3
Opened 2024-01-08 17:38 UTC by Helveg

Does this solve the issue?

2024-01-09 10:44 UTC, drodarie commented
Not sure it does: 
Tested with the file test_chunks.py from bsb-core on main branch. Currently the file contains an issue in the test (wrong import) so the test should fail in serial. Tested with the following commands in bsb-core:
`pytest tests/test_chunks.py`
`python -m unitest`
The test prints the expected error but is not considered as failed:
```
ERROR: test_default_chunk (tests.test_chunks.TestChunks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/toromis/Workspace/dbbs/bsb/bsb-test/bsb_test/parallel.py", line 90, in timed_f
    raise e
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/toromis/Workspace/dbbs/bsb/bsb-core/tests/test_chunks.py", line 20, in test_default_chunk
    self.test_single_chunk()
  File "/home/toromis/Workspace/dbbs/bsb/bsb-test/bsb_test/parallel.py", line 90, in timed_f
    raise e
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/toromis/Workspace/dbbs/bsb/bsb-core/tests/test_chunks.py", line 35, in test_single_chunk
    from bsb_test.pyconfig import cfg_single
ModuleNotFoundError: No module named 'bsb_test.pyconfig'

======================================================================
ERROR: test_single_chunk (tests.test_chunks.TestChunks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/toromis/Workspace/dbbs/bsb/bsb-test/bsb_test/parallel.py", line 90, in timed_f
    raise e
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/toromis/Workspace/dbbs/bsb/bsb-core/tests/test_chunks.py", line 35, in test_single_chunk
    from bsb_test.pyconfig import cfg_single
ModuleNotFoundError: No module named 'bsb_test.pyconfig'

```
It seems the program believes it runs in parallel?

2024-01-09 10:47 UTC, drodarie requested changes

2024-01-09 10:47 UTC, drodarie commented on bsb_test/parallel.py
>                  if MPI.get_size() > 1:
This test seems to be not sufficient to differentiate the cases in parallel and in serial.

2024-01-09 14:30 UTC, drodarie approved these changes
Works with `python -m unittest test_chunks`.
For pytest, works with the command `pytest test_chunks.py -p no:threadexception`

2024-01-10 11:41 UTC, Helveg commented
I added a note to the README: https://github.com/dbbs-lab/bsb-test/blob/main/README.md

2024-01-10 11:42 UTC, merged